#!/bin/bash
# mac_setup.sh — One-time Mac Mini configuration for Flutter iOS builds
# Usage: bash scripts/mac_setup.sh <mac-mini-ip> <mac-username>
# Run from Ubuntu. SSH key auth must already be set up.

set -e
PLUGIN_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

MAC_IP="$1"
MAC_USER="$2"

if [ -z "$MAC_IP" ] || [ -z "$MAC_USER" ]; then
  echo "Usage: bash \"$PLUGIN_ROOT/flutter-context/scripts/mac_setup.sh\" <mac-mini-ip> <mac-username>"
  echo "Example: bash \"$PLUGIN_ROOT/flutter-context/scripts/mac_setup.sh\" 192.168.1.42 john"
  exit 1
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Mac Mini Flutter Build Setup"
echo "  Target: $MAC_USER@$MAC_IP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ── Step 1: Verify SSH access ─────────────────────────────────────────────────
echo "[ 1/6 ] Verifying SSH access..."
if ! ssh -o ConnectTimeout=5 "$MAC_USER@$MAC_IP" "echo ok" &>/dev/null; then
  echo "  ❌ Cannot SSH to $MAC_USER@$MAC_IP"
  echo "  Fix: ssh-copy-id $MAC_USER@$MAC_IP"
  exit 1
fi
echo "  ✅ SSH access confirmed"

# ── Step 2: Install Homebrew (if missing) ─────────────────────────────────────
echo ""
echo "[ 2/6 ] Checking Homebrew..."
ssh "$MAC_USER@$MAC_IP" '
  if ! command -v brew &>/dev/null; then
    echo "  Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo '\''eval "$(/opt/homebrew/bin/brew shellenv)"'\'' >> ~/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
  else
    echo "  Homebrew already installed: $(brew --version | head -1)"
  fi
'
echo "  ✅ Homebrew ready"

# ── Step 3: Install Flutter ───────────────────────────────────────────────────
echo ""
echo "[ 3/6 ] Checking Flutter..."
ssh "$MAC_USER@$MAC_IP" '
  export PATH="$PATH:$HOME/flutter/bin"
  if ! command -v flutter &>/dev/null; then
    echo "  Installing Flutter..."
    cd ~
    git clone https://github.com/flutter/flutter.git -b stable --depth 1
    echo '\''export PATH="$PATH:$HOME/flutter/bin"'\'' >> ~/.zprofile
    export PATH="$PATH:$HOME/flutter/bin"
    flutter precache --ios
  else
    echo "  Flutter already installed: $(flutter --version | head -1)"
  fi
'
echo "  ✅ Flutter ready"

# ── Step 4: Install CocoaPods + ios-deploy ────────────────────────────────────
echo ""
echo "[ 4/6 ] Installing iOS tooling..."
ssh "$MAC_USER@$MAC_IP" '
  eval "$(/opt/homebrew/bin/brew shellenv)"

  if ! command -v pod &>/dev/null; then
    echo "  Installing CocoaPods..."
    sudo gem install cocoapods
  else
    echo "  CocoaPods: $(pod --version)"
  fi

  if ! command -v ios-deploy &>/dev/null; then
    echo "  Installing ios-deploy..."
    brew install ios-deploy
  else
    echo "  ios-deploy: $(ios-deploy --version)"
  fi
'
echo "  ✅ iOS tooling ready"

# ── Step 5: Accept Xcode license ─────────────────────────────────────────────
echo ""
echo "[ 5/6 ] Checking Xcode license..."
ssh "$MAC_USER@$MAC_IP" '
  if ! xcodebuild -version &>/dev/null; then
    echo "  ❌ Xcode not installed — install from App Store on Mac Mini, then re-run"
    exit 1
  fi
  sudo xcodebuild -license accept 2>/dev/null || true
  echo "  Xcode: $(xcodebuild -version | head -1)"
'
echo "  ✅ Xcode ready"

# ── Step 6: Save config on Ubuntu ────────────────────────────────────────────
echo ""
echo "[ 6/6 ] Saving config..."
CONFIG_FILE="$HOME/.flutter_build_config"
cat > "$CONFIG_FILE" <<EOF
# Flutter build config — auto-generated by mac_setup.sh
MAC_MINI_IP=$MAC_IP
MAC_MINI_USER=$MAC_USER
MAC_PROJECT_DIR=~/flutter_builds/$(basename $(pwd))
EOF
echo "  ✅ Config saved to $CONFIG_FILE"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ Mac Mini is ready for Flutter iOS builds"
echo ""
echo "  Connect your iPhone to the Mac Mini via USB, then:"
echo "  bash \"$PLUGIN_ROOT/flutter-context/scripts/build_ios.sh\""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
